### ISSUE TITLE
Connection failure with Mosquitto

### ISSUE THREAD

**Issue by shimatai** [gmag11/MQTT-MQL5-Library#1]
Which MQTT server did you use to run [the example](https://github.com/gmag11/MQTT-MQL5-Library/blob/master/example/mqttTest.mq5)?

I'm trying to run this example using [Mosquitto ](https://mosquitto.org/) on its latest version. Mosquitto also supports MQTT versions 3.1 and 3.1.1

I added my Mosquitto server address on the Expert Advisors allowed URLs for WebRequest and I'm still getting connection failure.

**Comment by EnziinSystem** [comment]
EA on MT5 enables only port 80/443.

So you need to change the port in the example to 80 or 443

MQTT server also listens on port 80 or 443.

Change the port on the server from 1883/8883 to 80/443

```
sudo systemctl stop mosquitto

sudo apt-get install redir

sudo redir :80 :1883

sudo systemctl start mosquitto
```

![Screenshot 2024-02-18 211207](https://github.com/gmag11/MQTT-MQL5-Library/assets/25495466/25e46aef-a6d6-4e03-9cbd-2934f0ea9b01)
![Screenshot 2024-02-18 211241](https://github.com/gmag11/MQTT-MQL5-Library/assets/25495466/8d2a0a30-47a8-454c-9778-5af9b0a90e89)

**Comment by gmag11** [comment]
Actually I did use standard 8883 port for SSL and 1883 for plain MQTT. You need to set the port permission in MT5 like xxx.xxx.xxx.xxx:1883

I used a local Mosquito Docker instance
